### ISSUE TITLE
Show tree view of a branch displayed in Gitbucket.

### ISSUE THREAD

**Issue by himeyon** [gitbucket-plugins/gitbucket-explorer-plugin#1]
The same is title meaning.

**Comment by tomoki1207** [comment]
At now, it cannot view non-default branch because of ~~[this line](https://github.com/tomoki1207/gitbucket-explorer-plugin/blob/master/src/main/scala/io/github/gitbucket/explorer/controllers/ExplorerController.scala#L32)~~. [this line](https://github.com/tomoki1207/gitbucket-explorer-plugin/blob/master/scripts/components/Root.js#L12)
But It might be more convenience showing selected branch.
